### GET list of authors
GET http://localhost:8000/api/authors

### Get author by id
GET http://localhost:8000/api/authors/1

### POST add a new author to the server
POST http://localhost:8000/api/authors
Content-Type: application/json

{
    "firstName": "Cow",
    "lastName": "Lassan"
}

### Delete the user
DELETE http://localhost:8000/api/authors/5